version: '2'
services:
  node:
    image: node:14-slim
    working_dir: /app
    volumes:
      - ./:/app:delegated
    command: yarn start
    restart: always
    environment:
      NODE_ENV: dev
    ports:
      - '8001:3000'