version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    depends_on:
      - db
    ports:
      - '8000:80'
  db:
    container_name: db
    image: postgres:9.6
    restart: always
    volumes:
      - "/data/moscow-depersonalization-data/pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=moscow-depersonalization-data
      - POSTGRES_USER=dmitrii
      - POSTGRES_PASSWORD=dev