version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    depends_on:
      - postgres
    ports:
      - '8000:80'
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-moscow-depersonalization-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=moscow-depersonalization-data
      - POSTGRES_USER=dmitrii
      - POSTGRES_PASSWORD=dev
volumes:
  postgres-moscow-depersonalization-data:
