version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    depends_on:
      - postgres
    ports:
      - '8000:80'
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=moscow-depersonalization-data
      - POSTGRES_USER=dmitrii
      - POSTGRES_PASSWORD=dev
volumes:
  postgres:
